services:
  servicea:
    image: servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    networks:
      - monitoring-network
        
        
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Metrics extension
      - "13133:13133" # Health check
    networks:
      - monitoring-network

  # Prometheus for metrics storage
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # UI
      - "14250:14250"  # Model
      - "14268:14268"  # Jaeger-collector HTTP
    networks:
      - monitoring-network

  # Vector for log processing
  vector:
    image: timberio/vector:0.45.0-debian
    volumes:
      - ./configs/vector.toml:/etc/vector/vector.toml
    ports:
      - "8383:8383"  # Vector API server
    networks:
      - monitoring-network

  # ClickHouse for log storage
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./configs/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./configs/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml
      - ./configs/clickhouse-users.xml:/etc/clickhouse-server/users.d/logging.xml
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    networks:
      - monitoring-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger
      - clickhouse
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus-data:
  clickhouse-data:
  grafana-data: