version: '3.8'

networks:
  monitoring-network:
    driver: bridge

services:
  zookeeper:
    image: zookeeper:latest
    platform: linux/arm64
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    #      ZOO_MY_ID: 1
    #      ZOO_PORT: 2181
    #      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ../data/zookeeper/data:/data
      - ../data/zookeeper/datalog:/datalog
    networks:
      - monitoring-network

  kafka1:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-con
    volumes:
      - ../data/kafka1/data:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - monitoring-network

#  kafka2:
#    image: confluentinc/cp-kafka:latest
#    platform: linux/arm64
#    hostname: kafka2
#    ports:
#      - "9093:9093"
#    environment:
#      - KAFKA_BROKER_ID=2
#      - CLUSTER_ID=2
#      - KAFKA_PROCESS_ROLES=broker
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENERS=PLAINTEXT://:9093
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9093
#      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
#      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
#    volumes:
#      - ../data/kafka-data:/bitnami/kafka
#    depends_on:
#      - zookeeper
#    networks:
#      - monitoring-network
#
#  kafka3:
#    image: confluentinc/cp-kafka:latest
#    platform: linux/arm64
#    hostname: kafka3
#    ports:
#      - "9094:9094"
#    environment:
#      - KAFKA_BROKER_ID=3
#      - CLUSTER_ID=3
#      - KAFKA_PROCESS_ROLES=broker
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENERS=PLAINTEXT://:9094
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9094
#      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
#    volumes:
#      - ../data/kafka-data:/bitnami/kafka
#    depends_on:
#      - zookeeper
#    networks:
#      - monitoring-network