receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 102400
  
  batch/clickhouse:
    timeout: 5s
    send_batch_size: 100000
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 100000
  
  memory_limiter/clickhouse:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "dotnet_monitoring"

  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  otlp/vector:
    endpoint: "vector:4317"
    tls:
      insecure: true
  
  
  clickhouse:
    endpoint: "tcp://clickhouse:9000"
    database: otel
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    ttl: 12h
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s


service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ prometheus ]
    
    traces:
      receivers: [ otlp ]
      #      processors: [ memory_limiter, batch ]
      processors: [ memory_limiter/clickhouse, batch/clickhouse ]
      exporters: [ clickhouse ]
    
    logs:
      receivers: [ otlp ]
      #      processors: [ memory_limiter, batch ]
      processors: [ memory_limiter/clickhouse, batch/clickhouse ]
      exporters: [ clickhouse ]
      #      receivers: [ otlp ]
      #      processors: [ memory_limiter, batch ]
      #      exporters: [ otlp/vector ]
      