global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  ### >OPENTELEMETRY
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:8889' ]
        labels:
          group: 'monitoring'
  
  ### >PROMETHEUS
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          group: 'monitoring'
  
  ### >CLICKHOUSE
  - job_name: 'clickhouse'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'clickhouse:9363' ]
        labels:
          group: 'monitoring'
  
  ### >VECTOR
  - job_name: 'vector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'vector:9598' ]
        labels:
          group: 'monitoring'
  
  ### >NET SERVICES
  - job_name: 'services_a'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'service_a:8080' ]
        labels:
          group: 'service'

  - job_name: 'services_b'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'service_a:8081' ]
        labels:
          group: 'service'

  - job_name: 'services_auth'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'service_a:8082' ]
        labels:
          group: 'service'
  
  ### >MSSQL
  - job_name: 'mssql'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'mssql:1433' ]
        labels:
          group: 'infra'
  
  ### >REDIS
  - job_name: redis-exporter
    scrape_interval: 15s
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
        labels:
          group: 'infra'
          #  - job_name: 'redis_exporter'
          #    scrape_interval: 30s
          #    scrape_timeout: 30s
          #    metrics_path: /  # For v2, use /v2
          ##    scheme: https
          #    tls_config:
          #      insecure_skip_verify: true
          #    static_configs:
          #      - targets: [ 'redis-service:8070' ]
          #        labels:
          #          group: 'infra'


          
        