global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          group: 'collector'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'prometheus'
          
  - job_name: 'services'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'service_a:8080' ]
        labels:
          group: 'service'
          
  - job_name: 'clickhouse'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'clickhouse:9363' ]
        labels:
          group: 'processor'