# Vector's API server
[api]
enabled = true
address = "0.0.0.0:8383"

# Data sources
[sources.otel_grpc]
type = "opentelemetry"
address = "0.0.0.0:4317"

# Transformations
[transforms.parse_logs]
type = "remap"
inputs = ["otel_grpc"]
source = '''
# Extract relevant fields
. = parse_json!(string!(.message))
'''

# Data sinks
[sinks.clickhouse_logs]
type = "clickhouse"
inputs = ["parse_logs"]
database = "logs"
endpoint = "http://clickhouse:8123"
table = "logs"
skip_unknown_fields = true
compression = "gzip"

# Health checks
[sinks.clickhouse_logs.healthcheck]
enabled = true